//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.24 at 07:50:07 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://in28minutes/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package in28minutes.courses;
